$(()=>{
    $("#ocultar").click((event)=>{
        event.preventDefault();
        $("#capaefectos").hide("slow");
    });
    $("#mostrar").click((event)=>{
        event.preventDefault();
        $("#capaefectos").show(1000);
    });
});